### ISSUE TITLE
PDF View Cross-browser

### ISSUE THREAD

**Issue by leventgunay** [oveo/mt-craft-web#25]
Firefox ve IE oncelikli olarak test ve iyilestirmeler yapılabilir.

**Comment by leventgunay** [comment]
merhaba, benim şuan için uygulamayı Windows ve IE ortamlarında test edebilme şansım bulunmuyor. eğer herhangi bir browserda hata gorurseniz işletim sistemi ve hata bilgileri dahilinde ayrı issuelar üzerinden tartısabiliriz. @gozcalik @sinahakman

**Comment by gozcalik** [comment]
Selam Levent, tamamdır, ben test ederim IE'de, github üzerinden takip ederiz issueları yine.
