### ISSUE TITLE
Task queue bittiğinde IE ve Firefox'ta loading gif sonsuza kadar dönüyor

### ISSUE THREAD

**Issue by gozcalik** [oveo/mt-craft-web#34]
Chrome'da bir süre sonra Tekrar Dene sayfasına düşüyor istendiği gibi. Diğer browser'larda da bu sayfaya gitmeli.

Aslında bu case'i detect edip şöyle bir şeyler yazdırabilsek çok iyi olur:

"Şu an doğrulanmamış tutanak bulunmamaktadır. Bir süre sonra tekrar deneyiniz."

**Comment by leventgunay** [comment]
fixed.
