### ISSUE TITLE
Tutanaklari onaylarken Enter'a basinca, hata sayfasina gidiyor.

### ISSUE THREAD

**Issue by sinahakman** [oveo/mt-craft-web#55]
Kaydet'e tiklanmis gibi olmali diye dusunuyorum....

**Comment by leventgunay** [comment]
bu hatayı suan tekrarlayamıyorum. @kel-sakal-biyik Uğur, eğer en son yapılan değişiklikler ile düzeldiyse ya da hala gecerli olup olmadıgıyla ilgili yorumlayabilir misin? teşekkürler.

**Comment by kel-sakal-biyik** [comment]
En son yaptığım değişiklikten sonra düzelmiş olduğunu umuyordum. Senin de testinde tekrarlanmadıysa çözülmüş demekir.




Teşekkürler



—
