### ISSUE TITLE
Login sorunu

### ISSUE THREAD

**Issue by dsilahcilar** [oveo/mt-craft-web#64]
En son update'ten sonra eger kullanici login olmadan islem'e giderse be'den 403 donuyor ama onyuzden sonsuz bir dongu ile event cekmeye calisiliyor. Sayfayi elle kapatmadikca devam ediyor.

**Comment by leventgunay** [comment]
selam Deniz, ben bunu test etmis ve duzeltmistim diye hatirliyorum.
Guncellenmemis js yuzunden olabilir mi browser dahilinde? Ayrica bugun, en
gec yarin bakabilirim tekrar.

**Comment by dsilahcilar** [comment]
Selam Levent, 

Sanirim browser cache'le alakali bir sorunmus. Ctrl+R den sonra ben de tekrar etmedim hatayi.
